"""Build the presentation deck as a PDF.

Uses ReportLab (open source, BSD-license). The deck is intentionally a
"data engineering principal review" deck - one idea per slide, callouts
in bullet form, and every chart referenced is regenerated by the pipeline
so the deck is always consistent with the underlying numbers.

Outline:
  1. Title
  2. Problem & approach
  3. Architecture
  4. Data profiling & cleaning decisions
  5. Feature engineering
  6. Data quality framework
  7. Portfolio health (3A)
  8. Credit x NPS (3B)
  9. Data gaps & improvements (3C)
 10. Reproducibility appendix
"""
from __future__ import annotations

import csv
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

from utils import ANNEX_ROOT


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------
PAGE = landscape(A4)
MARGIN = 1.4 * cm

styles = getSampleStyleSheet()
TITLE = ParagraphStyle(
    "TitleX", parent=styles["Title"],
    fontSize=26, leading=30, alignment=0, spaceAfter=18,
    textColor=colors.HexColor("#0E2A47"),
)
H1 = ParagraphStyle(
    "H1X", parent=styles["Heading1"],
    fontSize=18, leading=22, spaceAfter=10,
    textColor=colors.HexColor("#0E2A47"),
)
H2 = ParagraphStyle(
    "H2X", parent=styles["Heading2"],
    fontSize=13, leading=16, spaceAfter=6,
    textColor=colors.HexColor("#114B7A"),
)
BODY = ParagraphStyle(
    "BodyX", parent=styles["BodyText"],
    fontSize=11.5, leading=15.5, spaceAfter=4,
)
NOTE = ParagraphStyle(
    "NoteX", parent=styles["BodyText"],
    fontSize=9.5, leading=12.5, textColor=colors.HexColor("#555"), italic=True,
)
BULLET = ParagraphStyle(
    "BulX", parent=BODY, leftIndent=18, bulletIndent=4, spaceAfter=2,
)


def bullets(items: list[str]) -> list[Paragraph]:
    return [Paragraph(f"&bull;&nbsp;&nbsp;{text}", BULLET) for text in items]


def fitted_image(path: Path, *, max_w_cm: float, max_h_cm: float) -> Image:
    img = Image(str(path))
    iw, ih = img.imageWidth, img.imageHeight
    scale = min((max_w_cm * cm) / iw, (max_h_cm * cm) / ih)
    img.drawWidth = iw * scale
    img.drawHeight = ih * scale
    return img


# ---------------------------------------------------------------------------
# Slide builders
# ---------------------------------------------------------------------------
def s_title(story):
    story += [
        Spacer(1, 4 * cm),
        Paragraph("ABC Phones - Credit Portfolio Data Engineering Solution", TITLE),
        Paragraph("From dirty spreadsheets to reproducible insight in a single command", H2),
        Spacer(1, 1.4 * cm),
        Paragraph(f"Author: Elly Kadenyo<br/>Date: {datetime.utcnow().strftime('%Y-%m-%d')}<br/>"
                  f"Stack: Python 3.13 + pandas + DuckDB (all open source, MIT/BSD)", BODY),
        Spacer(1, 1.0 * cm),
        Paragraph("This deck is generated from the same code path that builds the warehouse, "
                  "so every chart and KPI shown is reproducible by running "
                  "<font face='Courier'>scripts/run_pipeline.py</font>.", NOTE),
        PageBreak(),
    ]


def s_problem(story):
    story += [
        Paragraph("Problem & Approach", H1),
        Paragraph("Mission: build the data systems that make portfolio analysis reliable & repeatable.", H2),
        Spacer(1, 0.4 * cm),
    ]
    story += bullets([
        "<b>Three sources, three flavours of mess</b>: 5 credit CSV snapshots, "
        "a 4-sheet sales/customer Excel with ~1M padded blank rows, and an NPS survey with "
        "encoding artefacts.",
        "<b>Engineering priorities</b>: simplicity over cleverness, explainability over magic, "
        "and full reproducibility from <i>raw -> insight</i> in one CLI call.",
        "<b>Tech choices</b>: pandas + DuckDB (file-based, ANSI SQL, MIT). No cloud, no orchestrator, "
        "no proprietary tools - the same code lifts and shifts to Airflow + Snowflake when the "
        "company is ready.",
        "<b>Deliverables shipped</b>: profiling, cleaning, feature engineering, ETL "
        "orchestrator, 7-check DQ framework, analyst-ready warehouse, portfolio analysis, "
        "this deck.",
    ])
    story.append(PageBreak())


def s_arch(story, paths):
    story += [
        Paragraph("Architecture", H1),
        Paragraph("Medallion (raw -> staging -> curated -> warehouse) with cross-cutting observability.", H2),
        Spacer(1, 0.2 * cm),
        fitted_image(paths["arch"], max_w_cm=26, max_h_cm=12),
    ]
    story += bullets([
        "<b>Lane 2 (Ingest)</b> stamps the snapshot date from filenames and drops Excel's "
        "blank padding before any cleaning runs - prevents schema-drift bugs from later snapshots.",
        "<b>Lane 3 (Transform)</b> is three pure functions: cleaning, feature engineering, DQ. "
        "Each runs independently and writes to its own Parquet so any stage is re-runnable.",
        "<b>Lane 4 (Store)</b> uses DuckDB so analysts open the warehouse with a single command "
        "and the same SQL ports to Postgres or Snowflake.",
    ])
    story.append(PageBreak())


def s_profiling(story):
    story += [
        Paragraph("Profiling & Cleaning Decisions", H1),
        Paragraph("Findings from <font face='Courier'>scripts/data_profiling.py</font> drove every "
                  "rule in <font face='Courier'>data_cleaning.py</font>.", H2),
    ]
    data = [
        ["Observation", "Cleaning rule applied"],
        ["Sales/DOB/Income sheets padded to 1,048,575 rows (Excel's max)",
         "Drop rows where every key column is NaN; we recover real row counts"],
        ["`Loan Id ` header has trailing space; `Loan Id` vs `loan_id` mixed case",
         "Normalise headers -> snake_case via NFKD + regex; strip mojibake (`U+FFFD`)"],
        ["`Unnamed: 28` appears in Q2/Q3/Q4 credit CSVs but not Q1",
         "Drop `unnamed_*` columns after normalisation - tolerant to schema drift"],
        ["Mixed date formats: `1/1/2025` (credit), `2025-01-15T00:00:00+03:00` (DOB)",
         "Multi-format parser tries default then day-first; strip timezone"],
        ["`CUSTOMER_AGE` is days-since-sale, not the customer's age in years",
         "Rename to `loan_age_days`; derive real age from DOB at snapshot date"],
        ["Loan IDs occasionally duplicate across snapshots (e.g. corrections)",
         "Dedup primary key (loan_id, snapshot_date), tie-break on max_payment_date"],
    ]
    tbl = Table(data, colWidths=[12 * cm, 14 * cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#114B7A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
            [colors.HexColor("#F2F6FA"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(tbl)
    story.append(PageBreak())


def s_features(story):
    story += [
        Paragraph("Feature Engineering", H1),
        Paragraph("Four derived features, all driven by config so band edges can be tuned without "
                  "code changes.", H2),
    ]
    data = [
        ["Feature", "Definition", "Edges / rules"],
        ["age_band",
         "<font face='Courier'>(snapshot_date - date_of_birth) / 365.25</font>, floor",
         "18-25 / 26-35 / 36-45 / 46-55 / 55+"],
        ["avg_monthly_income_band",
         "Income panel <font face='Courier'>received / duration</font> months",
         "8 bands from &lt;5k to 150k+ KES"],
        ["days_past_due",
         "From credit snapshot, clipped at 0",
         "Integer; 0 = current"],
        ["risk_category",
         "Tiered rules: status -> L2 bucket -> DPD threshold",
         "Critical / High / Medium / Low; first-match-wins"],
    ]
    tbl = Table(data, colWidths=[6 * cm, 11 * cm, 9 * cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#114B7A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTSIZE", (0, 0), (-1, -1), 10.5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
            [colors.HexColor("#F2F6FA"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(tbl)
    story += bullets([
        "Risk rules <i>and</i> band edges live in <font face='Courier'>config/pipeline.yaml</font> - "
        "a credit officer can recalibrate without touching Python.",
        "Coverage on DOB-derived age is ~39% (sparse DOB upload). When missing, "
        "<font face='Courier'>age_band</font> stays NULL and the band 'Unknown' is shown.",
    ])
    story.append(PageBreak())


def s_quality(story, dq_results):
    story += [
        Paragraph("Data Quality Framework", H1),
        Paragraph("7 checks across freshness, structure, content. Each emits a structured alert.", H2),
    ]
    data = [["Check", "Severity", "Result", "Observed"]]
    for r in dq_results:
        data.append([r["name"], r["severity"], r["status"], r["observed"]])
    tbl = Table(data, colWidths=[7 * cm, 3 * cm, 3 * cm, 13 * cm])
    style = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#114B7A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
            [colors.HexColor("#F2F6FA"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("PADDING", (0, 0), (-1, -1), 5),
    ])
    # Highlight FAIL rows
    for i, row in enumerate(data[1:], start=1):
        if row[2] == "FAIL":
            style.add("BACKGROUND", (0, i), (-1, i), colors.HexColor("#FCE3E3"))
    tbl.setStyle(style)
    story.append(tbl)
    story += bullets([
        "Real anomaly detected by FRESHNESS: latest snapshot is >100 days old vs the reference "
        "calendar - exactly the kind of stale-pipeline signal we want analysts to never see.",
        "Alerts are routed by severity in <font face='Courier'>config/pipeline.yaml</font> - "
        "Critical -> email + Slack + PagerDuty, Medium -> email only.",
        "DQ also exists as ANSI SQL: <font face='Courier'>sql/quality_checks.sql</font> runs against "
        "the warehouse for analysts.",
    ])
    story.append(PageBreak())


def s_portfolio(story, paths, metrics_rows):
    """Portfolio health: KPI trend + segment drill-downs on a single slide."""
    story += [
        Paragraph("Portfolio Health (3A)", H1),
        Paragraph("KPI trend across 5 snapshots, with age & income segment drill-downs.", H2),
    ]

    # Top row: KPI trend chart (large, on the left) + headline KPI table (right)
    first = metrics_rows[0]
    last  = metrics_rows[-1]
    kpi_data = [
        ["KPI", "First", "Last"],
        ["Delinquency",      f"{float(first['delinquency_rate']):.1%}", f"{float(last['delinquency_rate']):.1%}"],
        ["PAR 30",           f"{float(first['par30_rate']):.1%}",       f"{float(last['par30_rate']):.1%}"],
        ["Write-off",        f"{float(first['write_off_rate']):.1%}",   f"{float(last['write_off_rate']):.1%}"],
        ["Paid-off",         f"{float(first['paid_off_rate']):.1%}",    f"{float(last['paid_off_rate']):.1%}"],
        ["Collection rate",  f"{float(first['collection_rate']):.1%}",  f"{float(last['collection_rate']):.1%}"],
    ]
    kpi_tbl = Table(kpi_data, colWidths=[4.5 * cm, 2.5 * cm, 2.5 * cm])
    kpi_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#114B7A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
            [colors.HexColor("#F2F6FA"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("PADDING", (0, 0), (-1, -1), 3),
    ]))
    top_row = Table(
        [[fitted_image(paths["chart_trend"], max_w_cm=13, max_h_cm=5.5), kpi_tbl]],
        colWidths=[14 * cm, 10 * cm],
    )
    top_row.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                                 ("PADDING", (0, 0), (-1, -1), 1)]))
    story.append(top_row)

    # Bottom row: age & income drill-down charts side by side
    if paths.get("chart_age") and paths.get("chart_income"):
        bot_row = Table(
            [[fitted_image(paths["chart_age"],    max_w_cm=11.5, max_h_cm=5.2),
              fitted_image(paths["chart_income"], max_w_cm=11.5, max_h_cm=5.2)]],
            colWidths=[12 * cm, 12 * cm],
        )
        bot_row.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"),
                                     ("PADDING", (0, 0), (-1, -1), 1)]))
        story.append(bot_row)

    story += [Paragraph(
        "<b>Insights.</b> 18-25 cohort tops delinquency every snapshot (tighten credit "
        "thresholds / require co-signer). &lt;10k KES/month band defaults the most "
        "(offer weekly cadence aligned with informal-sector cash inflows).",
        BODY)]
    story.append(PageBreak())


def s_nps(story, paths, nps_rows):
    story += [
        Paragraph("Credit Outcomes x Customer Experience (3B)", H1),
        Paragraph("NPS deteriorates monotonically as days-past-due grows.", H2),
    ]
    # Build the NPS x DPD table
    spread_table = [["DPD bucket", "Respondents", "Avg NPS", "Promoter %", "Detractor %"]]
    for r in nps_rows:
        spread_table.append([
            r["dpd_bucket"], f"{int(float(r['respondents'])):,}",
            f"{float(r['avg_nps']):.2f}",
            f"{float(r['promoter_rate']) * 100:.1f}%",
            f"{float(r['detractor_rate']) * 100:.1f}%",
        ])
    tbl = Table(spread_table, colWidths=[2.6 * cm, 2.4 * cm, 2.0 * cm, 2.2 * cm, 2.3 * cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#114B7A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
            [colors.HexColor("#F2F6FA"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("PADDING", (0, 0), (-1, -1), 3),
    ]))
    # Place chart + table side-by-side to save vertical space
    side = Table(
        [[fitted_image(paths["chart_nps"], max_w_cm=14, max_h_cm=8), tbl]],
        colWidths=[15 * cm, 12 * cm],
    )
    side.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                              ("PADDING", (0, 0), (-1, -1), 2)]))
    story.append(side)
    story += bullets([
        "<b>Recommendation</b>: route PAR 7-30 accounts to a low-friction MoApp self-cure flow "
        "<i>before</i> a human collector calls. Recovers cash sooner and protects NPS.",
        "<b>Second action</b>: split NPS surveying so satisfaction questions and payment-difficulty "
        "questions are sent on different days to avoid recency bias.",
    ])
    story.append(PageBreak())


def s_gaps(story):
    story += [
        Paragraph("Data Gaps & Future Improvements (3C)", H1),
        Paragraph("Honest critique - what's blocking the next mile of analysis.", H2),
    ]
    story += [Paragraph("<b>Missing</b>", H2)]
    story += bullets([
        "No employment-type, no county / region, no per-transaction ledger (only balances).",
        "No device cost-of-goods, so loss given default can't be computed.",
        "Customer identity is conflated with loan_id - one person, many loans, no single view.",
    ])
    story += [Spacer(1, 0.2 * cm), Paragraph("<b>Inconsistent</b>", H2)]
    story += bullets([
        "Date formats vary across files; one date column even mixes timezones.",
        "Excel sheets pad to 1M rows with blanks - a single bad consumer crashes downstream.",
        "Schema drift: later credit snapshots add `Unnamed: 28`, breaking naive readers.",
    ])
    story += [Spacer(1, 0.2 * cm), Paragraph("<b>Ambiguous</b>", H2)]
    story += bullets([
        "`CUSTOMER_AGE` is days-since-sale per the data dictionary - the name lies.",
        "`ACCOUNT_STATUS_L1` mixes lifecycle (Inactive) with DPD bands (01-07) in one string.",
    ])
    story += [Spacer(1, 0.2 * cm), Paragraph("<b>Proposed improvements</b>", H2)]
    story += bullets([
        "Replace Excel uploads with an event-sourced ingestion (Kafka or Airbyte) - kills "
        "blank-row padding and gives an append-only audit trail.",
        "Split status into two orthogonal columns: <font face='Courier'>lifecycle_status</font> "
        "and <font face='Courier'>dpd_bucket</font>. Analysts already do this with regex.",
        "Promote <font face='Courier'>customer_id</font> to first-class so multi-loan customers "
        "can be analysed as people, not as loans.",
    ])
    story.append(PageBreak())


def s_repro(story):
    story += [
        Paragraph("Reproducibility & Operations", H1),
        Paragraph("Everything you see in this deck was produced by these five commands.", H2),
    ]
    cmd = (
        "<font face='Courier'>"
        "git clone &lt;repo&gt; &amp;&amp; cd Annex_DE_Elly_Kadenyo<br/>"
        "python -m venv .venv &amp;&amp; .venv/Scripts/activate.ps1<br/>"
        "pip install -r requirements.txt<br/>"
        "python scripts/run_pipeline.py --warehouse-fresh<br/>"
        "python scripts/make_architecture.py &amp;&amp; python scripts/make_slides.py"
        "</font>"
    )
    story.append(Paragraph(cmd, BODY))
    story += [Spacer(1, 0.4 * cm), Paragraph("What you get out:", H2)]
    story += bullets([
        "<font face='Courier'>data/warehouse/abc_phones.duckdb</font> - open with "
        "<font face='Courier'>duckdb data/warehouse/abc_phones.duckdb</font> and run any SQL.",
        "<font face='Courier'>outputs/*.csv, outputs/charts/*.png, outputs/insights.md</font> - "
        "for analysts and the C-suite.",
        "<font face='Courier'>outputs/dq_results.json, logs/pipeline-*.jsonl</font> - for the "
        "on-call data engineer.",
        "<font face='Courier'>slides/Annex_DE_Presentation.pdf</font> - this deck.",
    ])
    story += [Spacer(1, 0.4 * cm), Paragraph("Scheduling:", H2)]
    story += bullets([
        "Wire the orchestrator into Airflow / cron / GitHub Actions with one PythonOperator. "
        "It's idempotent and uses snapshot-date filenames, so re-runs are safe.",
        "Late-arriving snapshots: drop the new CSV in the Credit Data folder; the run picks it "
        "up next cycle - no DB migration needed.",
    ])


# ---------------------------------------------------------------------------
# Wire it up
# ---------------------------------------------------------------------------
def _read_csv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _read_json(path: Path) -> list[dict]:
    import json
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8"))


def build(out_path: Path) -> None:
    outputs = ANNEX_ROOT / "outputs"
    charts = outputs / "charts"
    paths = {
        "arch":         ANNEX_ROOT / "pipeline_design" / "architecture.png",
        "chart_trend":  charts / "portfolio_trend.png",
        "chart_age":    charts / "delinquency_by_age.png",
        "chart_income": charts / "delinquency_by_income.png",
        "chart_risk":   charts / "risk_mix.png",
        "chart_nps":    charts / "nps_by_dpd.png",
    }

    metrics_rows = _read_csv(outputs / "portfolio_metrics.csv")
    nps_rows = _read_csv(outputs / "nps_by_dpd_bucket.csv")
    dq_results = _read_json(outputs / "dq_results.json")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=PAGE,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=MARGIN,
        title="ABC Phones - DE Solution", author="Elly Kadenyo",
    )
    story: list = []
    s_title(story)
    s_problem(story)
    s_arch(story, paths)
    s_profiling(story)
    s_features(story)
    s_quality(story, dq_results)
    s_portfolio(story, paths, metrics_rows)
    s_nps(story, paths, nps_rows)
    s_gaps(story)
    s_repro(story)
    doc.build(story)


if __name__ == "__main__":
    out = ANNEX_ROOT / "slides" / "Annex_DE_Presentation.pdf"
    build(out)
    print(f"OK  slides -> {out}")
